import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaqu
 */
public class VentanaReporte extends javax.swing.JFrame {

    /**
     * Creates new form VentanaReporte
     */
    public VentanaReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    
    public void mostrarEventos() {
        String rutaArchivo = "C:\\Users\\joaqu\\OneDrive\\Documentos\\NetBeansProjects\\menu nvo\\menu nvo\\src\\main\\java\\eventos.csv";
        mostrarArchivoEnTextArea(rutaArchivo, jTextArea1);
    }

    private void mostrarArchivoEnTextArea(String rutaArchivo, javax.swing.JTextArea textArea) {
        StringBuilder sb = new StringBuilder();
        String linea;

        try (BufferedReader br = new BufferedReader(new FileReader(rutaArchivo))) {
            br.readLine();
            while ((linea = br.readLine()) != null) {
                String[] campos = linea.split(",");
                if (campos.length < 5) {
                    continue;
                }
                String formattedLine = String.format("ID: %-10s Nombre: %-20s Ubicación: %-20s Entradas: %-10s Precio de Entrada: %-10s%n", 
                        campos[0], campos[1], campos[2], campos[3], campos[4]);
                sb.append(formattedLine);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        textArea.setText(sb.toString());
    }



    public void mostrarUsuarios() {
        String rutaArchivo = "C:\\Users\\joaqu\\OneDrive\\Documentos\\NetBeansProjects\\menu nvo\\menu nvo\\src\\main\\java\\usuarios.csv";
        mostrarArchivoEnTextAreaUsuarios(rutaArchivo, jTextArea2);
    }

    private void mostrarArchivoEnTextAreaUsuarios(String rutaArchivo, javax.swing.JTextArea textArea) {
        StringBuilder sb = new StringBuilder();
        String linea;

        try (BufferedReader br = new BufferedReader(new FileReader(rutaArchivo))) {
            br.readLine();
            while ((linea = br.readLine()) != null) {
                if (linea.trim().isEmpty()) {
                    continue; // Si la línea está vacía, ignórala
                }
                String[] campos = linea.split(",");
                sb.append("RUT: ").append(campos[0])
                        .append("\tContraseña: ").append(campos[1])
                        .append("\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        textArea.setText(sb.toString());
    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration                   
}
